services:
  artificialgateway:
    build: .
    working_dir: /app
    command: 
      - python 
      - -m
      - mosaic_subnet.cli
      - gateway
      - agent.ArtificialGateway 
      - agent.ArtificialGateway 
      - "0.0.0.0" 
      - "50050"
    ports: 
    - 50050:50050
    volumes:
      - .:/app
      - /home/bakobi/.cache/huggingface:/root/.cache/huggingface
      - /home/bakobi/.commune:/root/.commune
    environment:
      - PYTHONFAULTHANDLER=1 
      - PYTHONUNBUFFERED=1 
      - PYTHONHASHSEED=random 
      - PIP_NO_CACHE_DIR=off 
      - PIP_DISABLE_PIP_VERSION_CHECK=on 
      - PIP_DEFAULT_TIMEOUT=100 
      - POETRY_NO_INTERACTION=1 
      - POETRY_VIRTUALENVS_CREATE=false 
      - POETRY_CACHE_DIR='/var/cache/pypoetry' 
      - POETRY_HOME='/usr/local' 
      - POETRY_VERSION=1.8.2
      - CUDA_VISIBLE_DEVICES=7
      - CUDA_DOCKER_ARCH=compute_90
      - CUDA_MODULE_LOADING=Lazy
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids:
                - "7"
  artificialminer:
    build: .
    working_dir: /app
    command: 
      - python 
      - -m
      - mosaic_subnet.cli
      - miner
      - agent.ArtificialMiner
      - agent.ArtificialMiner
      - "0.0.0.0" 
      - "50056"
    ports: 
    - 50056:50056
    volumes:
      - .:/app
      - /home/bakobi/.cache/huggingface:/root/.cache/huggingface
      - /home/bakobi/.commune:/root/.commune
    environment:
      - PYTHONFAULTHANDLER=1 
      - PYTHONUNBUFFERED=1 
      - PYTHONHASHSEED=random 
      - PIP_NO_CACHE_DIR=off 
      - PIP_DISABLE_PIP_VERSION_CHECK=on 
      - PIP_DEFAULT_TIMEOUT=100 
      - POETRY_NO_INTERACTION=1 
      - POETRY_VIRTUALENVS_CREATE=false 
      - POETRY_CACHE_DIR='/var/cache/pypoetry' 
      - POETRY_HOME='/usr/local' 
      - POETRY_VERSION=1.8.2
      - CUDA_VISIBLE_DEVICES=6
      - CUDA_DOCKER_ARCH=compute_90
      - CUDA_MODULE_LOADING=LAZY
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids:
                - '7'
  artificialminer:
    build: .
    working_dir: /app
    command: 
      - python 
      - -m
      - mosaic_subnet.cli
      - miner
      - agent.ArtificialMiner
      - agent.ArtificialMiner
      - "0.0.0.0" 
      - "50056"
    ports: 
    - 50056:50056
    volumes:
      - .:/app
      - /home/bakobi/.cache/huggingface:/root/.cache/huggingface
      - /home/bakobi/.commune:/root/.commune
    environment:
      - PYTHONFAULTHANDLER=1 
      - PYTHONUNBUFFERED=1 
      - PYTHONHASHSEED=random 
      - PIP_NO_CACHE_DIR=off 
      - PIP_DISABLE_PIP_VERSION_CHECK=on 
      - PIP_DEFAULT_TIMEOUT=100 
      - POETRY_NO_INTERACTION=1 
      - POETRY_VIRTUALENVS_CREATE=false 
      - POETRY_CACHE_DIR='/var/cache/pypoetry' 
      - POETRY_HOME='/usr/local' 
      - POETRY_VERSION=1.8.2
      - CUDA_VISIBLE_DEVICES=6
      - CUDA_DOCKER_ARCH=compute_90
      - CUDA_MODULE_LOADING=LAZY
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids:
                - '6'

  artificialminer_1:
    build: .
    working_dir: /app
    command: 
      - python 
      - -m
      - mosaic_subnet.cli
      - miner
      - agent.ArtificialMiner_1
      - agent.ArtificialMiner_1
      - "0.0.0.0" 
      - "50051"
    ports: 
    - 50051:50051
    volumes:
      - .:/app
      - /home/bakobi/.cache/huggingface:/root/.cache/huggingface
      - /home/bakobi/.commune:/root/.commune
    environment:
      - PYTHONFAULTHANDLER=1 
      - PYTHONUNBUFFERED=1 
      - PYTHONHASHSEED=random 
      - PIP_NO_CACHE_DIR=off 
      - PIP_DISABLE_PIP_VERSION_CHECK=on 
      - PIP_DEFAULT_TIMEOUT=100 
      - POETRY_NO_INTERACTION=1 
      - POETRY_VIRTUALENVS_CREATE=false 
      - POETRY_CACHE_DIR='/var/cache/pypoetry' 
      - POETRY_HOME='/usr/local' 
      - POETRY_VERSION=1.8.2
      - CUDA_VISIBLE_DEVICES=1
      - CUDA_DOCKER_ARCH=compute_90
      - CUDA_MODULE_LOADING=LAZY
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids:
                - "1"

  artificialminer_2:
    build: .
    working_dir: /app
    image: mosaic:latest
    command: 
      - python 
      - -m
      - mosaic_subnet.cli
      - miner
      - agent.ArtificialMiner_2
      - agent.ArtificialMiner_2
      - "0.0.0.0" 
      - "50052"
    ports: 
    - 50052:50052
    volumes:
      - .:/app
      - /home/bakobi/.cache/huggingface:/root/.cache/huggingface
      - /home/bakobi/.commune:/root/.commune
    environment:
      - PYTHONFAULTHANDLER=1 
      - PYTHONUNBUFFERED=1 
      - PYTHONHASHSEED=random 
      - PIP_NO_CACHE_DIR=off 
      - PIP_DISABLE_PIP_VERSION_CHECK=on 
      - PIP_DEFAULT_TIMEOUT=100 
      - POETRY_NO_INTERACTION=1 
      - POETRY_VIRTUALENVS_CREATE=false 
      - POETRY_CACHE_DIR='/var/cache/pypoetry' 
      - POETRY_HOME='/usr/local' 
      - POETRY_VERSION=1.8.2
      - CUDA_VISIBLE_DEVICES=2
      - CUDA_DOCKER_ARCH=compute_90
      - CUDA_MODULE_LOADING=LAZY
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids:
                - "2"

  artificialminer_3:
    build: .
    working_dir: /app
    image: mosaic:latest
    command: 
      - python 
      - -m
      - mosaic_subnet.cli
      - miner
      - agent.ArtificialMiner_3
      - agent.ArtificialMiner_3
      - "0.0.0.0" 
      - "50053"
    ports: 
    - 50053:50053
    volumes:
      - .:/app
      - /home/bakobi/.cache/huggingface:/root/.cache/huggingface
      - /home/bakobi/.commune:/root/.commune
    environment:
      - PYTHONFAULTHANDLER=1 
      - PYTHONUNBUFFERED=1 
      - PYTHONHASHSEED=random 
      - PIP_NO_CACHE_DIR=off 
      - PIP_DISABLE_PIP_VERSION_CHECK=on 
      - PIP_DEFAULT_TIMEOUT=100 
      - POETRY_NO_INTERACTION=1 
      - POETRY_VIRTUALENVS_CREATE=false 
      - POETRY_CACHE_DIR='/var/cache/pypoetry' 
      - POETRY_HOME='/usr/local' 
      - POETRY_VERSION=1.8.2
      - CUDA_VISIBLE_DEVICES=3
      - CUDA_DOCKER_ARCH=compute_90
      - CUDA_MODULE_LOADING=LAZY
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids:
                - "3"

  artificialminer_4:
    build: .
    working_dir: /app
    image: mosaic:latest
    command: 
      - python 
      - -m
      - mosaic_subnet.cli
      - miner
      - agent.ArtificialMiner_4
      - agent.ArtificialMiner_4
      - "0.0.0.0" 
      - "50054"
    ports: 
    - 50054:50054
    volumes:
      - .:/app
      - /home/bakobi/.cache/huggingface:/root/.cache/huggingface
      - /home/bakobi/.commune:/root/.commune
    environment:
      - PYTHONFAULTHANDLER=1 
      - PYTHONUNBUFFERED=1 
      - PYTHONHASHSEED=random 
      - PIP_NO_CACHE_DIR=off 
      - PIP_DISABLE_PIP_VERSION_CHECK=on 
      - PIP_DEFAULT_TIMEOUT=100 
      - POETRY_NO_INTERACTION=1 
      - POETRY_VIRTUALENVS_CREATE=false 
      - POETRY_CACHE_DIR='/var/cache/pypoetry' 
      - POETRY_HOME='/usr/local' 
      - POETRY_VERSION=1.8.2
      - CUDA_VISIBLE_DEVICES=4
      - CUDA_DOCKER_ARCH=compute_90
      - CUDA_MODULE_LOADING=LAZY
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids:
                - "4"

  artificialminer_5:
    build: .
    working_dir: /app
    image: mosaic:latest
    command: 
      - python 
      - -m
      - mosaic_subnet.cli
      - miner
      - agent.ArtificialMiner_5
      - agent.ArtificialMiner_5
      - "0.0.0.0" 
      - "50055"
    ports: 
    - 50055:50055
    volumes:
      - .:/app
      - /home/bakobi/.cache/huggingface:/root/.cache/huggingface
      - /home/bakobi/.commune:/root/.commune
    environment:
      - PYTHONFAULTHANDLER=1 
      - PYTHONUNBUFFERED=1 
      - PYTHONHASHSEED=random 
      - PIP_NO_CACHE_DIR=off 
      - PIP_DISABLE_PIP_VERSION_CHECK=on 
      - PIP_DEFAULT_TIMEOUT=100 
      - POETRY_NO_INTERACTION=1 
      - POETRY_VIRTUALENVS_CREATE=false 
      - POETRY_CACHE_DIR='/var/cache/pypoetry' 
      - POETRY_HOME='/usr/local' 
      - POETRY_VERSION=1.8.2
      - CUDA_VISIBLE_DEVICES=5
      - CUDA_DOCKER_ARCH=compute_90
      - CUDA_MODULE_LOADING=LAZY
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids:
                - "5"
              